# expand aliases set in bash_profile
kubectl create ns auth
kubectl create secret tls login.furiouscat.com.tls --cert=ssl/cert.pem --key=ssl/key.pem -n auth
kubectl create secret tls dex.furiouscat.com.tls --cert=ssl/cert.pem --key=ssl/key.pem -n auth
# CA ( ca.pem generated by gencert.sh) configmap
kubectl create -f ca-cm.yml
# Login App configuration
kubectl create -f loginapp-cm.yml
# Login App service
kubectl create -f loginapp-ing-svc.yml
# Login App Deployment
kubectl create -f loginapp-deploy.yml

kubectl create -f dex-crd.yml

#Create Dex resources:
# Dex configuration
kubectl create -f dex-cm.yml
# Dex service
kubectl create -f dex-ing-svc.yml
# Dex deployment
kubectl create -f dex-deploy.yml

kubectl create -f rbac.yml
